### ISSUE TITLE
can't build main branch on my Mac at home

### ISSUE THREAD

**Issue by nburchha** [JonahKoellner/transendence#56]
Django tries to migrate some baselobby_ptr but can't because not in interactive mode

it worked a few days ago. will check if it still works with an older version.

```bash
WARN[0000] /Users/niklasburchhardt/Dev/transcendence/transendence_dev_env/docker-compose.yml: `version` is obsolete 
[+] Building 52.6s (23/23) FINISHED                                                                    docker:desktop-linux
 => [django internal] load build definition from Dockerfile                                                            0.0s
 => => transferring dockerfile: 839B                                                                                   0.0s
 => [django internal] load metadata for docker.io/library/python:3.9-slim                                              1.4s
 => [django internal] load .dockerignore                                                                               0.0s
 => => transferring context: 2B                                                                                        0.0s
 => [django 1/6] FROM docker.io/library/python:3.9-slim@sha256:4ee0613170ac55ebc693a03b6655a5c6f387126f6bc3390e739c2e  0.0s
 => [django internal] load build context                                                                               0.1s
 => => transferring context: 1.64MB                                                                                    0.0s
 => CACHED [django 2/6] WORKDIR /app                                                                                   0.0s
 => [django 3/6] COPY . .                                                                                              0.1s
 => [django 4/6] RUN apt-get update && apt-get install -y     build-essential     libpq-dev     && rm -rf /var/lib/a  29.3s
 => [django 5/6] RUN pip install --no-cache-dir -r requirements.txt                                                   18.1s 
 => [django 6/6] RUN pip install daphne                                                                                1.2s 
 => [django] exporting to image                                                                                        0.9s 
 => => exporting layers                                                                                                0.9s 
 => => writing image sha256:ef518bb28c2cf266fa62db0f969c5f3b436cdb5591afeab28e26b7c29b7f8781                           0.0s 
 => => naming to docker.io/library/transendence_dev_env-django                                                         0.0s 
 => [angular internal] load build definition from Dockerfile                                                           0.0s 
 => => transferring dockerfile: 1.70kB                                                                                 0.0s 
 => [angular internal] load metadata for docker.io/library/node:20                                                     0.9s
 => [angular internal] load .dockerignore                                                                              0.0s
 => => transferring context: 2B                                                                                        0.0s
 => [angular 1/7] FROM docker.io/library/node:20@sha256:f4755c9039bdeec5c736b2e0dd5b47700d6393b65688b9e9f807ec12f54a8  0.0s
 => [angular internal] load build context                                                                              0.1s
 => => transferring context: 173.78kB                                                                                  0.1s
 => CACHED [angular 2/7] WORKDIR /app                                                                                  0.0s
 => CACHED [angular 3/7] RUN npm install -g @angular/cli@16.2.6                                                        0.0s
 => CACHED [angular 4/7] COPY package*.json ./                                                                         0.0s
 => CACHED [angular 5/7] RUN npm install --legacy-peer-deps &&     npm uninstall ng2-charts chart.js                   0.0s
 => CACHED [angular 6/7] RUN npm install chart.js@^4.4.5 ng2-charts@5.0.0 --legacy-peer-deps                           0.0s
 => CACHED [angular 7/7] COPY . .                                                                                      0.0s
 => [angular] exporting to image                                                                                       0.0s
 => => exporting layers                                                                                                0.0s
 => => writing image sha256:fe5721f66a2cb9115e0172437590509ad9996dc92254bee8fcd7192f4840ddee                           0.0s
 => => naming to docker.io/library/transendence_dev_env-angular                                                        0.0s
[+] Running 2/6
 ✔ Network transendence_dev_env_webnet          Created                                                                0.1s 
 ✔ Volume "transendence_dev_env_postgres_data"  Created                                                                0.0s 
 ⠏ Container transendence_dev_env-db-1          Created                                                                7.9s 
 ⠏ Container transendence_dev_env-redis-1       Created                                                                7.9s 
 ⠇ Container transendence_dev_env-django-1      Created                                                                7.8s 
 ⠧ Container transendence_dev_env-angular-1     Created                                                                7.7s 
Attaching to angular-1, db-1, django-1, redis-1
redis-1    | 1:C 19 Dec 2024 11:34:57.656 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-1    | 1:C 19 Dec 2024 11:34:57.656 # Redis version=6.2.16, bits=64, commit=00000000, modified=0, pid=1, just started
redis-1    | 1:C 19 Dec 2024 11:34:57.656 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis-1    | 1:M 19 Dec 2024 11:34:57.657 * monotonic clock: POSIX clock_gettime
redis-1    | 1:M 19 Dec 2024 11:34:57.661 * Running mode=standalone, port=6379.
redis-1    | 1:M 19 Dec 2024 11:34:57.661 # Server initialized
redis-1    | 1:M 19 Dec 2024 11:34:57.663 * Ready to accept connections
db-1       | The files belonging to this database system will be owned by user "postgres".
db-1       | This user must also own the server process.
db-1       | 
db-1       | The database cluster will be initialized with locale "en_US.utf8".
db-1       | The default database encoding has accordingly been set to "UTF8".
db-1       | The default text search configuration will be set to "english".
db-1       | 
db-1       | Data page checksums are disabled.
db-1       | 
db-1       | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1       | creating subdirectories ... ok
db-1       | selecting dynamic shared memory implementation ... posix
db-1       | selecting default "max_connections" ... 100
db-1       | selecting default "shared_buffers" ... 128MB
db-1       | selecting default time zone ... Etc/UTC
db-1       | creating configuration files ... ok
db-1       | running bootstrap script ... ok
db-1       | performing post-bootstrap initialization ... ok
db-1       | syncing data to disk ... ok
db-1       | 
db-1       | 
db-1       | Success. You can now start the database server using:
db-1       | 
db-1       |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1       | 
db-1       | initdb: warning: enabling "trust" authentication for local connections
db-1       | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1       | waiting for server to start....2024-12-19 11:34:58.497 UTC [48] LOG:  starting PostgreSQL 17.2 (Debian 17.2-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1       | 2024-12-19 11:34:58.500 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1       | 2024-12-19 11:34:58.509 UTC [51] LOG:  database system was shut down at 2024-12-19 11:34:58 UTC
db-1       | 2024-12-19 11:34:58.523 UTC [48] LOG:  database system is ready to accept connections
db-1       |  done
db-1       | server started
db-1       | CREATE DATABASE
db-1       | 
db-1       | 
db-1       | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db-1       | 
db-1       | waiting for server to shut down....2024-12-19 11:34:58.729 UTC [48] LOG:  received fast shutdown request
db-1       | 2024-12-19 11:34:58.730 UTC [48] LOG:  aborting any active transactions
db-1       | 2024-12-19 11:34:58.735 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1       | 2024-12-19 11:34:58.735 UTC [49] LOG:  shutting down
db-1       | 2024-12-19 11:34:58.736 UTC [49] LOG:  checkpoint starting: shutdown immediate
angular-1  | 
angular-1  | Warning: This is a simple server for use in testing or debugging Angular applications
angular-1  | locally. It hasn't been reviewed for security issues.
angular-1  | 
angular-1  | Binding this server to an open connection can result in compromising your application or
angular-1  | computer. Using a different host than the one passed to the "--host" flag might result in
angular-1  | websocket connection issues. You might need to use "--disable-host-check" if that's the
angular-1  | case.
angular-1  |     
db-1       | 2024-12-19 11:34:58.826 UTC [49] LOG:  checkpoint complete: wrote 921 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.039 s, sync=0.041 s, total=0.092 s; sync files=301, longest=0.006 s, average=0.001 s; distance=4238 kB, estimate=4238 kB; lsn=0/1908948, redo lsn=0/1908948
db-1       | 2024-12-19 11:34:58.832 UTC [48] LOG:  database system is shut down
db-1       |  done
db-1       | server stopped
db-1       | 
db-1       | PostgreSQL init process complete; ready for start up.
db-1       | 
db-1       | 2024-12-19 11:34:58.986 UTC [1] LOG:  starting PostgreSQL 17.2 (Debian 17.2-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1       | 2024-12-19 11:34:58.987 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1       | 2024-12-19 11:34:58.987 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1       | 2024-12-19 11:34:58.990 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1       | 2024-12-19 11:34:58.997 UTC [64] LOG:  database system was shut down at 2024-12-19 11:34:58 UTC
db-1       | 2024-12-19 11:34:59.004 UTC [1] LOG:  database system is ready to accept connections
angular-1  | ****************************************************************************************
angular-1  | This is a simple server for use in testing or debugging Angular applications locally.
angular-1  | It hasn't been reviewed for security issues.
angular-1  | 
angular-1  | DON'T USE IT FOR PRODUCTION!
angular-1  | ****************************************************************************************
angular-1  | - Generating browser application bundles (phase: setup)...
django-1   | DEBUG (0.004) 
django-1   |             SELECT
django-1   |                 c.relname,
django-1   |                 CASE
django-1   |                     WHEN c.relispartition THEN 'p'
django-1   |                     WHEN c.relkind IN ('m', 'v') THEN 'v'
django-1   |                     ELSE 't'
django-1   |                 END,
django-1   |                 obj_description(c.oid, 'pg_class')
django-1   |             FROM pg_catalog.pg_class c
django-1   |             LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
django-1   |             WHERE c.relkind IN ('f', 'm', 'p', 'r', 'v')
django-1   |                 AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
django-1   |                 AND pg_catalog.pg_table_is_visible(c.oid)
django-1   |         ; args=None; alias=default
django-1   | DEBUG (0.004) 
django-1   |             SELECT
django-1   |                 c.relname,
django-1   |                 CASE
django-1   |                     WHEN c.relispartition THEN 'p'
django-1   |                     WHEN c.relkind IN ('m', 'v') THEN 'v'
django-1   |                     ELSE 't'
django-1   |                 END,
django-1   |                 obj_description(c.oid, 'pg_class')
django-1   |             FROM pg_catalog.pg_class c
django-1   |             LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
django-1   |             WHERE c.relkind IN ('f', 'm', 'p', 'r', 'v')
django-1   |                 AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
django-1   |                 AND pg_catalog.pg_table_is_visible(c.oid)
django-1   |         ; args=None; alias=default
angular-1  |     Components styles sourcemaps are not generated when styles optimization is enabled.
django-1   | Database is unavailable, retrying in 2 seconds... [1/10]
django-1   | Database connection established successfully.
django-1   | It is impossible to add a non-nullable field 'baselobby_ptr' to chaoslobby without specifying a default. This is because the database needs something to populate existing rows.
django-1   | Please select a fix:
django-1   |  1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
django-1   |  2) Quit and manually define a default value in models.py.
django-1   | Traceback (most recent call last):
django-1   |   File "/app/manage.py", line 59, in <module>
django-1   |     main()
django-1   |   File "/app/manage.py", line 56, in main
django-1   |     execute_from_command_line(sys.argv)
django-1   |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
django-1   |     utility.execute()
django-1   |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
django-1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
django-1   |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
django-1   |     self.execute(*args, **cmd_options)
django-1   |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 458, in execute
django-1   |     output = self.handle(*args, **options)
django-1   |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 106, in wrapper
django-1   |     res = handle_func(*args, **kwargs)
django-1   |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/makemigrations.py", line 235, in handle
django-1   |     changes = autodetector.changes(
django-1   |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/autodetector.py", line 46, in changes
django-1   |     changes = self._detect_changes(convert_apps, graph)
django-1   |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/autodetector.py", line 196, in _detect_changes
django-1   |     self.generate_added_fields()
django-1   |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/autodetector.py", line 1026, in generate_added_fields
django-1   |     self._generate_added_field(app_label, model_name, field_name)
django-1   |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/autodetector.py", line 1059, in _generate_added_field
django-1   |     field.default = self.questioner.ask_not_null_addition(
django-1   |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/questioner.py", line 169, in ask_not_null_addition
django-1   |     choice = self._choice_input(
django-1   |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/questioner.py", line 114, in _choice_input
django-1   |     result = input()
django-1   | EOFError: EOF when reading a line
django-1   | Select an option: 
django-1 exited with code 1
```

**Comment by nburchha** [comment]
doesnt work with an older commit on the main branch, django still tries to migrate some shit and fails because its non interactive but wants input

**Comment by LukeDerpwalka** [comment]
Skill issue deleting migrations
